# Generated by Django 5.2.8 on 2025-11-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_card_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(default='#2a92bf', help_text='Color en formato hexadecimal (ej: #2a92bf)', max_length=7),
        ),
    ]
